base_url: "http://127.0.0.1:7860"
sd_model: "anythingV5Anything_anythingV5PrtRE"
sd_vae: "None"
output_dir: "./output"
controlnet_base: "cn.png"
mask: "mask.png"
prompt: "1girl, tareme,  pink hair, twintails, red eyes, hime cut, masterpiece, high quality, 
cute, highres, delicate, beautiful detailed, finely detailed, front light, white background, 
standing, sfw, looking at viewer, (upper body:1.1)"
